function _y(){
    _section() {
        echo ""
        echo ""
        echo ""
        echo "###########################################################################################"
        echo "#    $1"
        echo "###########################################################################################"
    }
    _section $1
    yay -S $1
}

_y 2048.c
_y bash-pipes
_y bottom-bin
_y c-lolcat
_y cava-git
_y cbonsai-git
_y cpufetch-git
_y ddgr
_y duf-bin
_y figlet-fonts
_y figlet-fonts-extra
_y fish-fzf
_y fisher
_y fontpreview-ueberzug-git
_y fzf-extras
_y ghq-bin
_y git-delta-bin
_y globe-cli-bin
_y gotop-bin
_y i3-scrot
_y kosugi-regular
_y kvantum-theme-qogir-git
_y lazygit-bin
_y lightdm-mini-greeter
_y makefontpkg
_y matcha-gtk-theme
_y matcha-kde-git
_y nkf
_y otf-takaoex
_y pacman4console
_y pacwatch
_y pandoc-bin
_y paru-bin
_y peco-bin
_y picom-jonaburg-git
_y powershell-bin
_y qogir-gtk-theme
_y qt5-styleplugins
_y rofi-greenclip
_y shell-color-scripts
_y shellcheck-bin
_y slack-desktop
_y starship-bin
_y super_unko-git
_y textimg
_y tmux-nord-theme
_y toilet
_y ttf-cica
_y ttf-roboto-slab
_y tty-clock
_y typora
_y uwufetch
_y vimix-gtk-themes
_y vimix-icon-theme
_y vimix-theme-kde-git
_y ytfzf
_y zoxide-bin
