bold = true
color_mode = "ansi" # ansi, rgb or none
palette = "pastel" # default, darker, pastel or matrix
delay_ms = 10
inherit_style = false
kinds = ["heavy"] # heavy, light, curved, knobby, emoji, outline, dots
num_pipes = 1
reset_threshold = 0.5 # 0.0–1.0
turn_chance = 0.15 # 0.0–1.0
